Answer 1

In [ ]:
# importing numpy with alias name
import numpy as np

# creating a array using numpy arange
arr = np.arange(2, 50, 3)

# printing array
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


Answer 2

In [ ]:
#importing numpy with alias name
import numpy as np

#creating 2 empty lists
list_1 = []
list_2 = []

#getting values from user for list_1
for i in range(5):
  x=int(input("\nEnter values for list 1: "))
  list_1.append(x)

#print list_1
print("list 1", list_1)

#getting values from user for list_2
for i in range(5):
  x=int(input("\nEnter values for list 2: "))
  list_2.append(x)
  
#print list_2
print("list 2", list_2)
print(" ")

#converting lists 1 and list 2 to numpy arrays and printing arrays
array_1 = np.array(list_1)
print("array 1: ", array_1)
array_2 = np.array(list_2)
print("array 2: ", array_2)

#Concatenation of array 1 and array 2
arr_concat = np.concatenate((array_1, array_2))

#printing new array after concatenation
print("Array after concatenation is : ", arr_concat)

#sorting of concatenated array
print("sorted array is:", np.sort(arr_concat))



Enter values for list 1: 2

Enter values for list 1: 14

Enter values for list 1: 63

Enter values for list 1: 85

Enter values for list 1: 21
list 1 [2, 14, 63, 85, 21]

Enter values for list 2: 33

Enter values for list 2: 44

Enter values for list 2: 88

Enter values for list 2: 45

Enter values for list 2: 69
list 2 [33, 44, 88, 45, 69]
 
array 1:  [ 2 14 63 85 21]
array 2:  [33 44 88 45 69]
Array after concatenation is :  [ 2 14 63 85 21 33 44 88 45 69]
sorted array is: [ 2 14 21 33 44 45 63 69 85 88]


Answer 3


In [ ]:
# importing numpy as np
import numpy as np

# creating a 2d array
arr = np.array([[11,25,33,77],[14,39,55,37]])
print(arr)

#calculating diamension of ndarray
print("\nDimensions of array : ", arr.ndim)
 
# Printing size of array
print("\nSize of array : ", arr.size)


[[11 25 33 77]
 [14 39 55 37]]

Dimensions of array :  2

Size of array :  8


Answer 4

In [ ]:
#importing numpy
import numpy as np

# creating a 1d array
arr = np.arange(20)

#printing shape of array
print("\nShape of Array :",arr.shape)

# converting using newaxis in row wise
row_arr = arr[np.newaxis, :]
print("\nShape of 2d Array in row major :",row_arr.shape)

# converting using newaxis in column wise
col_arr = arr[:, np.newaxis]
print("\nShape of 2d Array in column major :",col_arr.shape)


Shape of Array : (20,)

Shape of 2d Array in row major : (1, 20)

Shape of 2d Array in column major : (20, 1)


Answer 5

In [ ]:
import numpy as np
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
print("Vertical stacking:\n", np.vstack((a, b)))
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


Answer 6

In [ ]:
import numpy as np
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print('Original Numpy Array:\n ', arr)
uniqueValues, occurCount = np.unique(arr, return_counts=True)
print('Unique Values :\n ',uniqueValues)
print("Occurrence Count :\n ", occurCount)
print('Unique Values along with occurrence Count')
listOfUniqueValues = zip(uniqueValues, occurCount)
for elem in listOfUniqueValues:
   print(elem[0] , ' Occurs : ' , elem[1], ' times')